import { loadState, saveState, createEmptyState } from "./storage.js";
import { generateSchedule } from "./mixer.js";

const app = document.querySelector("#app");
let state = loadState();
let activeCourtId = state.courts[0]?.id || "";
const persist = () => saveState(state);
const el = (tag, attrs = {}, children = []) => { const node = document.createElement(tag); Object.entries(attrs).forEach(([key, value]) => { if (key === "class") node.className = value; else if (key === "text") node.textContent = value; else node.setAttribute(key, value); }); children.forEach(child => node.append(child)); return node; };
const button = (text, className, handler) => { const node = el("button", { class: className, type: "button", text }); node.addEventListener("click", handler); return node; };
const shell = (title, subtitle) => { const root = el("div", { class: "app-shell" }); const header = el("header", { class: "topbar" }, [el("div", {}, [el("div", { class: "eyebrow", text: "PadelScore" }), el("h1", { class: "title", text: title }), el("div", { class: "subtle", text: subtitle })])]); root.append(header); return root; };
const showError = (node, message) => { node.textContent = message; node.hidden = false; };

function render() { app.replaceChildren(); if (state.session.status === "empty") renderEmpty(); else if (state.session.status === "setup") renderSetup(); else if (state.session.status === "players") renderPlayers(); else renderSchedule(); }

function renderEmpty() { const root = shell("Match kamu", "Atur rotasi padel dengan mudah"); const content = el("section", { class: "empty" }); const box = el("div"); box.append(el("div", { class: "empty-mark", text: "⌁" }), el("h2", { text: "Belum ada match" }), el("p", { text: "Buat sesi baru untuk mulai mix pemain dan menyusun jadwal pertandingan." }), button("＋  Buat Match", "primary-btn", () => { state.session.status = "setup"; persist(); render(); })); content.append(box); root.append(content); app.append(root); }

function renderSetup() { const root = shell("Buat Match", "Langkah 1 dari 3 · Atur sesi"); root.append(el("div", { class: "steps" }, [el("i", { class: "active" }), el("i"), el("i")])); const panel = el("form", { class: "panel" }); const error = el("div", { class: "error" }); error.hidden = true; const fields = {}; [["playerCount", "Jumlah pemain", 12, 4], ["courtCount", "Jumlah lapangan", 2, 1], ["durationHours", "Durasi sesi (jam)", 2, 0.1]].forEach(([key, label, value, min]) => { const wrap = el("div", { class: "field" }); wrap.append(el("label", { for: key, text: label })); const input = el("input", { class: "input", id: key, type: "number", min, step: key === "durationHours" ? "0.1" : "1", value }); fields[key] = input; wrap.append(input); if (key === "durationHours") wrap.append(el("div", { class: "subtle", text: "Rotasi otomatis setiap 10 menit" })); panel.append(wrap); }); panel.append(error, button("Create Match", "primary-btn wide", event => { event.preventDefault(); const players = Number(fields.playerCount.value); const courts = Number(fields.courtCount.value); const duration = Number(fields.durationHours.value); if (!Number.isInteger(players) || players < 4 || !Number.isInteger(courts) || courts < 1 || duration <= 0) return showError(error, "Isi jumlah pemain minimal 4, lapangan minimal 1, dan durasi lebih dari 0."); state.session = { status: "players", playerCount: players, courtCount: courts, durationHours: duration, slotMinutes: 10 }; state.players = Array.from({ length: players }, (_, index) => ({ id: `p${index + 1}`, name: "", matches: 0, wins: 0, byes: 0 })); state.courts = Array.from({ length: courts }, (_, index) => ({ id: `c${index + 1}`, name: `Court ${index + 1}` })); state.schedule = []; persist(); render(); })); root.append(panel); app.append(root); }

function renderPlayers() { const root = shell("Nama Pemain", `${state.session.playerCount} pemain · Langkah 2 dari 3`); root.append(el("div", { class: "steps" }, [el("i", { class: "active" }), el("i", { class: "active" }), el("i")])); const panel = el("form", { class: "panel" }); const list = el("div", { class: "name-list" }); const inputs = []; state.players.forEach((player, index) => { const row = el("div", { class: "name-row" }); row.append(el("span", { class: "name-number", text: String(index + 1).padStart(2, "0") })); const input = el("input", { class: "input", type: "text", placeholder: `Nama pemain ${index + 1}`, value: player.name, autocomplete: "off" }); input.addEventListener("input", () => { player.name = input.value; }); inputs.push(input); row.append(input); list.append(row); }); const error = el("div", { class: "error" }); error.hidden = true; panel.append(el("div", { class: "section-head" }, [el("h2", { text: "Isi semua nama pemain" }), el("span", { class: "subtle", text: `${state.players.length} nama` })]), list, error, button("Buat Jadwal Pertandingan", "primary-btn wide", event => { event.preventDefault(); const names = inputs.map(input => input.value.trim()); const normalized = names.map(name => name.toLocaleLowerCase()); if (names.some(name => !name)) return showError(error, "Semua nama pemain harus diisi."); if (new Set(normalized).size !== names.length) return showError(error, "Nama pemain tidak boleh duplikat."); state.players.forEach((player, index) => { player.name = names[index]; }); const result = generateSchedule({ players: state.players, courts: state.courts, durationHours: state.session.durationHours }); state.schedule = result.schedule; state.session.status = "schedule"; activeCourtId = state.courts[0].id; persist(); render(); })); root.append(panel); app.append(root); }

function renderSchedule() { const root = shell("Jadwal Pertandingan", `${state.session.durationHours} jam · interval 10 menit`); const header = el("div", { class: "summary" }, [el("strong", { text: `${state.schedule.length / state.courts.length} slot · ${state.courts.length} lapangan` }), el("span", { text: "Nama pemain terkunci · skor tetap bisa diedit" })]); root.append(header); const tabs = el("nav", { class: "court-tabs", "aria-label": "Pilih lapangan" }); state.courts.forEach(court => tabs.append(button(court.name, `court-tab ${court.id === activeCourtId ? "active" : ""}`, () => { activeCourtId = court.id; render(); }))); root.append(tabs); const list = el("section"); const court = state.courts.find(item => item.id === activeCourtId) || state.courts[0]; const items = state.schedule.filter(item => item.courtId === court.id); list.append(el("div", { class: "section-head" }, [el("h2", { text: court.name }), el("span", { class: "subtle", text: `${items.length} jadwal` })])); items.forEach(item => list.append(scheduleCard(item))); const bye = items[0]?.bye || []; if (bye.length) list.append(el("div", { class: "bye", text: `Istirahat slot ini: ${bye.map(id => state.players.find(player => player.id === id)?.name).join(" · ")}` })); root.append(list); const actions = el("div", { class: "footer-actions" }); actions.append(el("span", { class: "subtle", text: "Tersimpan otomatis" }), button("Reset sesi", "danger", () => { if (window.confirm("Hapus sesi dan semua jadwal?")) { state = createEmptyState(); persist(); render(); } })); root.append(actions); app.append(root); }

function scheduleCard(item) { const names = id => state.players.find(player => player.id === id)?.name || "-"; const minute = item.startMinute; const time = `${String(19 + Math.floor(minute / 60)).padStart(2, "0")}:${String(minute % 60).padStart(2, "0")}`; const end = `${String(19 + Math.floor((minute + 10) / 60)).padStart(2, "0")}:${String((minute + 10) % 60).padStart(2, "0")}`; const card = el("article", { class: `schedule-item ${item.finished ? "done" : item.slotIndex === 0 ? "live" : ""}` }); const status = item.finished ? "✓ Selesai" : item.slotIndex === 0 ? "● Sedang bermain" : "Berikutnya"; card.append(el("div", { class: "slot-head" }, [el("span", { text: `Slot ${String(item.slotIndex + 1).padStart(2, "0")} · ${time}–${end}` }), el("span", { class: item.finished || item.slotIndex === 0 ? "live-text" : "", text: status })])); const match = el("div", { class: "match" }); match.append(el("div", { class: "team", text: `${names(item.teamA[0])}\n${names(item.teamA[1])}` }));
  const scores = el("div", { class: "scores" }); scores.append(el("div", { class: "score-label", text: "SKOR" })); ["scoreA", "scoreB"].forEach(key => { const input = el("input", { type: "number", min: 0, inputmode: "numeric", value: item[key], "aria-label": key === "scoreA" ? "Skor tim kiri" : "Skor tim kanan" }); input.addEventListener("input", () => { item[key] = input.value; persist(); }); scores.append(input); }); match.append(scores, el("div", { class: "team right", text: `${names(item.teamB[0])}\n${names(item.teamB[1])}` })); card.append(match); const finish = button(item.finished ? "Edit skor" : "Finish pertandingan", "finish-btn", () => { item.finished = true; persist(); render(); }); card.append(finish); return card; }

render();
