import { loadState, saveState, createEmptyState } from "./storage.js";
import { generateSchedule } from "./mixer.js";

const app = document.querySelector("#app");
let state = loadState();
let activeCourtId = state.courts[0]?.id || "";
let expandedScheduleId = null;
const persist = () => saveState(state);
const el = (tag, attrs = {}, children = []) => { const node = document.createElement(tag); Object.entries(attrs).forEach(([key, value]) => { if (key === "class") node.className = value; else if (key === "text") node.textContent = value; else node.setAttribute(key, value); }); children.forEach(child => node.append(child)); return node; };
const button = (text, className, handler) => { const node = el("button", { class: className, type: "button", text }); node.addEventListener("click", handler); return node; };
const shell = (title, subtitle) => { const root = el("div", { class: "app-shell" }); const header = el("header", { class: "topbar" }, [el("div", {}, [el("div", { class: "eyebrow", text: "PadelScore" }), el("h1", { class: "title", text: title }), el("div", { class: "subtle", text: subtitle })])]); root.append(header); return root; };
const showError = (node, message) => { node.textContent = message; node.hidden = false; };

function render() { app.replaceChildren(); if (state.session.status === "empty") renderEmpty(); else if (state.session.status === "setup") renderSetup(); else if (state.session.status === "players") renderPlayers(); else renderSchedule(); }

function renderEmpty() { const root = shell("Match kamu", "Atur rotasi padel dengan mudah"); const content = el("section", { class: "empty" }); const box = el("div"); box.append(el("div", { class: "empty-mark", text: "⌁" }), el("h2", { text: "Belum ada match" }), el("p", { text: "Buat sesi baru untuk mulai mix pemain dan menyusun jadwal pertandingan." }), button("＋  Buat Match", "primary-btn", () => { state.session.status = "setup"; persist(); render(); })); content.append(box); root.append(content); app.append(root); }

function cancelDraft() { state = createEmptyState(); persist(); render(); }

function renderSetup() { const root = shell("Buat Match", "Langkah 1 dari 3 · Atur sesi"); root.append(el("div", { class: "steps" }, [el("i", { class: "active" }), el("i"), el("i")])); const panel = el("form", { class: "panel" }); const error = el("div", { class: "error" }); error.hidden = true; const fields = {}; [["playerCount", "Jumlah pemain", "Contoh: 12", 4], ["courtCount", "Jumlah lapangan", "Contoh: 2", 1], ["durationHours", "Durasi sesi (jam)", "Contoh: 2", 0.1]].forEach(([key, label, placeholder, min]) => { const wrap = el("div", { class: "field" }); wrap.append(el("label", { for: key, text: label })); const input = el("input", { class: "input", id: key, type: "number", min, step: key === "durationHours" ? "0.1" : "1", placeholder }); fields[key] = input; wrap.append(input); if (key === "durationHours") wrap.append(el("div", { class: "subtle", text: "Rotasi otomatis setiap 10 menit" })); panel.append(wrap); }); const actions = el("div", { class: "form-actions" }, [button("Create Match", "primary-btn wide", event => { event.preventDefault(); const players = Number(fields.playerCount.value); const courts = Number(fields.courtCount.value); const duration = Number(fields.durationHours.value); if (!Number.isInteger(players) || players < 4 || !Number.isInteger(courts) || courts < 1 || duration <= 0) return showError(error, "Isi jumlah pemain minimal 4, lapangan minimal 1, dan durasi lebih dari 0."); state.session = { status: "players", playerCount: players, courtCount: courts, durationHours: duration, slotMinutes: 10 }; state.players = Array.from({ length: players }, (_, index) => ({ id: `p${index + 1}`, name: "", matches: 0, wins: 0, byes: 0 })); state.courts = Array.from({ length: courts }, (_, index) => ({ id: `c${index + 1}`, name: `Court ${index + 1}` })); state.schedule = []; persist(); render(); }), button("Cancel", "secondary-btn wide", cancelDraft)]); panel.append(error, actions); root.append(panel); app.append(root); }

function renderPlayers() { const root = shell("Nama Pemain", `${state.session.playerCount} pemain · Langkah 2 dari 3`); root.append(el("div", { class: "steps" }, [el("i", { class: "active" }), el("i", { class: "active" }), el("i")])); const panel = el("form", { class: "panel" }); const list = el("div", { class: "name-list" }); const inputs = []; state.players.forEach((player, index) => { const row = el("div", { class: "name-row" }); row.append(el("span", { class: "name-number", text: String(index + 1).padStart(2, "0") })); const input = el("input", { class: "input", type: "text", placeholder: `Nama pemain ${index + 1}`, value: player.name, autocomplete: "off" }); input.addEventListener("input", () => { player.name = input.value; }); inputs.push(input); row.append(input); list.append(row); }); const error = el("div", { class: "error" }); error.hidden = true; const actions = el("div", { class: "form-actions" }, [button("Buat Jadwal Pertandingan", "primary-btn wide", event => { event.preventDefault(); const names = inputs.map(input => input.value.trim()); const normalized = names.map(name => name.toLocaleLowerCase()); if (names.some(name => !name)) return showError(error, "Semua nama pemain harus diisi."); if (new Set(normalized).size !== names.length) return showError(error, "Nama pemain tidak boleh duplikat."); state.players.forEach((player, index) => { player.name = names[index]; }); const result = generateSchedule({ players: state.players, courts: state.courts, durationHours: state.session.durationHours }); state.schedule = result.schedule; state.session.status = "schedule"; activeCourtId = state.courts[0].id; persist(); render(); }), button("Cancel", "secondary-btn wide", cancelDraft)]); panel.append(el("div", { class: "section-head" }, [el("h2", { text: "Isi semua nama pemain" }), el("span", { class: "subtle", text: `${state.players.length} nama` })]), list, error, actions); root.append(panel); app.append(root); }

function renderSchedule() { const root = shell("Jadwal Pertandingan", `${state.session.durationHours} jam`); const tabs = el("nav", { class: "court-tabs", "aria-label": "Pilih lapangan" }); state.courts.forEach(court => tabs.append(button(court.name, `court-tab ${court.id === activeCourtId ? "active" : ""}`, () => { activeCourtId = court.id; expandedScheduleId = null; render(); }))); root.append(tabs); const list = el("section"); const court = state.courts.find(item => item.id === activeCourtId) || state.courts[0]; const items = state.schedule.filter(item => item.courtId === court.id); const activeItem = items.find(item => item.started && !item.finished); const nextItem = items.find(item => !item.finished && !item.started); if (!expandedScheduleId || !items.some(item => item.id === expandedScheduleId)) expandedScheduleId = activeItem?.id || nextItem?.id; list.append(el("div", { class: "section-head" }, [el("h2", { text: court.name }), el("span", { class: "subtle", text: `${items.length} pertandingan` })])); items.forEach(item => list.append(scheduleCard(item, item.id === expandedScheduleId, !activeItem && item.id === nextItem?.id))); const bye = items[0]?.bye || []; if (bye.length) list.append(el("div", { class: "bye", text: `Istirahat slot ini: ${bye.map(id => state.players.find(player => player.id === id)?.name).join(" · ")}` })); root.append(list); const actions = el("div", { class: "footer-actions" }); actions.append(el("span", { class: "subtle", text: "Tersimpan otomatis" }), button("Reset sesi", "danger", () => { if (window.confirm("Hapus sesi dan semua jadwal?")) { state = createEmptyState(); persist(); render(); } })); root.append(actions); app.append(root); }

function scheduleCard(item, expanded, canStart) { const names = id => state.players.find(player => player.id === id)?.name || "-"; const active = item.started && !item.finished; const card = el("article", { class: `schedule-item ${item.finished ? "done" : active ? "live" : ""} ${expanded && active ? "expanded" : "collapsed"}` }); const status = item.finished ? "✓ Selesai" : active ? "● Sedang bermain" : ""; if (status) card.append(el("div", { class: "slot-head status-row" }, [el("span", { class: "live-text", text: status })])); const match = el("div", { class: "match" }); match.append(el("div", { class: "team", text: `${names(item.teamA[0])}\n${names(item.teamA[1])}` }));
  if (!active) { match.append(el("div", { class: "collapsed-score", text: item.scoreA || item.scoreB ? `${item.scoreA || 0} — ${item.scoreB || 0}` : "—" }), el("div", { class: "team right", text: `${names(item.teamB[0])}\n${names(item.teamB[1])}` })); card.append(match); if (item.finished) card.append(button("Edit", "more-btn", () => { item.finished = false; item.started = true; expandedScheduleId = item.id; persist(); render(); })); else if (canStart) card.append(button("Start", "more-btn start-btn", () => { item.started = true; expandedScheduleId = item.id; persist(); render(); })); return card; }
  const scores = el("div", { class: "scores" }); scores.append(el("div", { class: "score-label", text: "SKOR" })); ["scoreA", "scoreB"].forEach(key => { const input = el("input", { type: "number", min: 0, inputmode: "numeric", value: item[key], "aria-label": key === "scoreA" ? "Skor tim kiri" : "Skor tim kanan" }); input.addEventListener("input", () => { item[key] = input.value; persist(); }); scores.append(input); }); match.append(scores, el("div", { class: "team right", text: `${names(item.teamB[0])}\n${names(item.teamB[1])}` })); card.append(match, button("Finish pertandingan", "finish-btn", () => { item.finished = true; persist(); render(); })); return card; }

render();
